version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DATABASES: dev,test
    volumes:
      - ./scripts/pg-init-scripts:/docker-entrypoint-initdb.d
